language: python

matrix:
  include:
    - python: 3.7
      after_script:
        - bash ci/report-coverage.sh
    - name: flake8
      python: 3.7
      script: tox -e flake8

install: pip install tox-travis
script: tox

notifications:
  email:
    on_success: never
    on_failure: always
